version: '4.4'
networks:
  lb_network:
    driver: bridge
services:
  loadbalancer:
    build: ./LoadBalancer
    image: lbserver-app
    ports:
      - 5000:5000
    networks:
      - lb_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
  goserver:
    build: ./Server
    image: goserver-app
    ports:
      - 8000:8000